### ISSUE TITLE
Assembly for Javascript---infinite loop

### ISSUE THREAD

**Issue by narraritwin** [Headline/discord-compiler-bot#132]
The following code hasn't finished being compiled into assembly (via `;asm js`), and it's been 45 minutes.

```js
for (let i = 0; i<i+++--i; i+=i--+(++i)) {
  console.log(i);
}
```

**Comment by Headline** [comment]
Hi! Thanks for submitting

This is a duplicate of #121, the request never left the bot and errored out before any type of processing could take place. Only languages with the `*` in the `;languages` command can have their assembly viewed.

**Comment by narraritwin** [comment]
Perhaps the bot could reply with some message then? Such as
```
Cannot compile {language} to assembly.
```

**Comment by Headline** [comment]
Right, just submitted a patch to cover this. The change should now be reflected on the live bot. Thanks again!
