### ISSUE TITLE
Arbitary reqwest::Error

### ISSUE THREAD

**Issue by bootsareme** [Headline/discord-compiler-bot#134]
It happend literally yesterday when I wanted to run the .exe release file but instead I get:

`INFO  discord_compiler_bot > Registering owner(s): 559039176905850880
Error: reqwest::Error { kind: Decode, source: Error("missing field `provider`", line: 1, column: 1441) }`

Now sorry if I don't have more information, because I literally copied and paste the .env example from the root tree and I ran the standalone exe and I get this. It is not my bots fault as I verified other discord code working on my bots. But this might be Discord's new privacy policy or something but it literally work the day before.

**Comment by Headline** [comment]
Hi!

We've just patched this, it was due to a Wandbox API change. Can you try the v3.3.1 release once the binaries are published?

**Comment by bootsareme** [comment]
The issue is now resolved per the above comment.
