### ISSUE TITLE
command line arguments on file attachment

### ISSUE THREAD

**Issue by ThomasByr** [Headline/discord-compiler-bot#144]
Hello,

Suppose we send a single file (a file, not a code block) main.c
and we reply to our message with
```
;compile c
argv1 argv2
```
The bot considers argv1 and argv2 as files and not as command line arguments.
(the same behavior occurs when we reference a code in pastebin with `<`)

That would not occur if we typed in, in a single message

````
;compile c
argv1 argv2
```c
#include <stdio.h>

int main(int argc, char *argv[]) {
   ...
}
```
````

Am I missing something?

**Comment by Headline** [comment]
Hi - I'm unable to reproduce the issue, what exactly do you mean by files?


![](http://i.michaelwflaherty.com/u/5QmX8wKYe7.png)

**Comment by ThomasByr** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/48696364/164338303-8f06fdac-1e34-4534-9d81-07290c9e8129.png">

it only happens on replies :/

**Comment by Headline** [comment]
Can you also share the content of the replied message along with whatever file you're compiling here?

**Comment by ThomasByr** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/48696364/164339686-5984959a-8b5c-41af-9a87-c4b82205b061.png">
here is the same issue with your example file
