### ISSUE TITLE
Stderr output cuts itself

### ISSUE THREAD

**Issue by Iinksafe** [Headline/discord-compiler-bot#148]
Hi there! So I was compiling a code I made today and was going to test how it works on Compiler!

Basically, the standard error output (stderr) cuts itself in the embed's description.

I have attached an image for further understanding.
![IMG_20220425_015428](https://user-images.githubusercontent.com/78565096/165002174-8c329b12-7f57-419b-bdd3-a595e705bbaf.jpg)

**Comment by es183923** [comment]
It is defined here: https://github.com/Headline/discord-compiler-bot/blob/master/src/utls/constants.rs#L15-L16
Discord limits embed values to 1024 characters, which is way more than the 500/250 char limit defined here. https://discord.com/developers/docs/resources/channel#embed-object-embed-limits

**Comment by Headline** [comment]
Languages which have verbose outputs over our limit will always get truncated. The limit could get increased as mentioned, if someone beats me to it, we shouldn't be up against the limit too much, give us a hundred characters to play with. 

As for the output limit - it should remain at 250 to prevent channel spam

**Comment by Iinksafe** [comment]
Alright, thank you for the quick response!

**Comment by Headline** [comment]
I'd like to leave this open - we'll increase the error output limit
