### ISSUE TITLE
Bot can ping @everyone on command

### ISSUE THREAD

**Issue by ClaytonTDM** [Headline/discord-compiler-bot#172]
Running the ;compile command with @everyone set as the language like this:
![image](https://user-images.githubusercontent.com/71360210/174668977-058a89bd-1a4b-4476-b1e4-1ffbcadbd005.png)
will ping @everyone
Mabye to fix it, wrap the response in a codeblock.

**Comment by samast2010** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/66264481/175531711-9d54c1a1-2db9-4f14-867e-6fb143737f07.png">
You sure about this? Even with the bot having ping perms, it won't ping everyone at all.

**Comment by Headline** [comment]
Well, either way, fixed in #173
