### ISSUE TITLE
process.env (nodejs)

### ISSUE THREAD

**Issue by MigPlayer6032** [Headline/discord-compiler-bot#175]
Hello! I've been using the bot, and I imagine you should be careful with that.

![image](https://user-images.githubusercontent.com/96895505/182254205-0521c567-551b-4a0f-9cb5-239871da172b.png)

Usually the `process.env` of the nodejs has secret information of the bot, and I think that goes for you too.

**Comment by Headline** [comment]
Hi, thanks for keeping an eye out.

The bot itself and the execution service are two independent components.
See: wandbox.org beneath your request

Also, the execution of your program are jailed on the host environment and do not have internet access. You won't be able to persist any changes, destroy the vm, or make external requests.
