### ISSUE TITLE
Invalid bot configuration causes unintuitive response

### ISSUE THREAD

**Issue by Headline** [Headline/discord-compiler-bot#183]
![](https://media.discordapp.net/attachments/505722333970038794/1028849085152776192/unknown.png)

https://github.com/Headline/discord-compiler-bot/blob/1d2ed51a720a30b24b44a01a8165de8eb3a0915f/src/main.rs#L127

**Comment by ThomasByr** [comment]
couldn't the message be improved just by `unwrap_or_else` ?
```rs
let plog_parse = plog.parse::<u64>().unwrap_or_else(|_| {
    panic!("Unable to parse panic log channel id: {}", plog);
});
```
I mean it is not much as it doesn't solve anything but it improves the message...

**Comment by Headline** [comment]
> couldn't the message be improved just by `unwrap_or_else` ?
> 
> ```rust
> let plog_parse = plog.parse::<u64>().unwrap_or_else(|_| {
>     panic!("Unable to parse panic log channel id: {}", plog);
> });
> ```
> 
> I mean it is not much as it doesn't solve anything but it improves the message...

Yeah, exactly this would do. I don't want us to just exit with no indicator
