### ISSUE TITLE
It gives wrong output

### ISSUE THREAD

**Issue by ilker610** [Headline/discord-compiler-bot#188]
![image](https://user-images.githubusercontent.com/75069363/201529042-8108c03a-af92-4e93-a375-3fe14ed29c11.png)

```py
test = "merb"
print("{}",format(test))
```

**Comment by ThomasByr** [comment]
this is mainly due to the fact that format string in python do not work like this at all

please try
```py
test = 'merb'
print('{}'.format(test))  # or even better: print(f'{test}')
```
