### ISSUE TITLE
Support for ALGOL 68 Genie

### ISSUE THREAD

**Issue by pandasoli** [Headline/discord-compiler-bot#205]
I don't know how to implement it, so I would like let you guys know that I would like it in the bot.

This is the [download link](https://jmvdveer.home.xs4all.nl/en.download.algol-68-genie-current.html) for the `a68g` (the most new and better interpreter).  
And this is the "[main page](https://jmvdveer.home.xs4all.nl/en.algol-68-genie.html)" if you want.

**Comment by ThomasByr** [comment]
Hey 👋

If you want an other language/compiler installed, you should reder to [this](https://github.com/Headline/discord-compiler-bot/issues/86) issue

tl;dr: the bot does not compile anything and uses other services to process requests, so you can make a request there ([Godbolt](https://godbolt.org/) or [Wandbox](https://wandbox.org/))
