### ISSUE TITLE
The compiler bot dosen't seem to work.

### ISSUE THREAD

**Issue by Comptecho** [Headline/discord-compiler-bot#210]
The compiler bot dosen't seem to work, as it says it dosen't have reaction perms, but in fact it has all.

**Comment by ThomasByr** [comment]
Hello 👋
Please make sure the link you used to invite the bot is the following :
```txt
https://discord.com/oauth2/authorize?client_id=504095380166803466&permissions=379968&scope=applications.commands%20bot
```
Making the bot an admin is not necessary but shouldn't break things. Could you please confirm that no channel perms are "blocking" the bot from using emotes and custom emotes ?
