### ISSUE TITLE
quotes in a function silences output

### ISSUE THREAD

**Issue by abcq2** [Headline/discord-compiler-bot#213]
the following command unexpectedly produces no output
;compile
```c
#include <stdio.h>
int foo() { return '"'; }
int main() { puts("test"); }
```
---
the following commands produce the expected output
;compile
```c
#include <stdio.h>
int foo() { return '*'; }
int main() { puts("test"); }
```
;compile
```c
#include <stdio.h>
int main() { puts("test"); }
int foo() { return '"'; }
```
---
the following command produces a "redefinition of main" error
;compile
```c
#include <stdio.h>
// int foo() { return '"'; }
int main() { puts("test"); }
```

**Comment by abcq2** [comment]
the issue does not happen with `'\x22'`, only literal `'"'`

**Comment by Headline** [comment]
This is kind of an annoying problem - we allow some tolerance of shenanigans with the main detection, it works well for most cases, but yeah this is very broken.

https://github.com/Headline/discord-compiler-bot/commit/efbfe5b778cd25a7adb8851afca57a2baa4ee88d should get us most of the way there
