### ISSUE TITLE
Mislabeled size unit in a `;compile` failure message

### ISSUE THREAD

**Issue by imaami** [Headline/discord-compiler-bot#214]
Looks like the bot confused bytes and mebibytes. See the attached images, and my apologies for not writing a proper description; it's been a long day.

*Edit:* missed a thing in one of the images, reupload. Brain no make good

![01_-_upload](https://github.com/Headline/discord-compiler-bot/assets/3589345/3633e4d6-929b-4b5d-a057-1e0393ce083e)
![02_-_error](https://github.com/Headline/discord-compiler-bot/assets/3589345/d064fbeb-6f26-4840-8d59-4afc0d273d1a)

**Comment by Headline** [comment]
https://github.com/search?q=repo%3AHeadline%2Fdiscord-compiler-bot%20uploaded%20file%20too%20large&type=code

Yeah good catch - their units passed to apis may have changed.
