### ISSUE TITLE
Unable to use multiline stdin with code url

### ISSUE THREAD

**Issue by mikkelens** [Headline/discord-compiler-bot#217]
https://discord.com/channels/505721414662225921/505722198288367626/1154643341716238386
![image](https://github.com/Headline/discord-compiler-bot/assets/31762830/b95b6982-fe97-4e5a-a80e-8d7635a6f0a8)
<details>
<summary>Pipe operator at the end does not help (neither with nor without backticks (```)</summary>
<img src="https://github.com/Headline/discord-compiler-bot/assets/31762830/8de2e914-aae7-4e1c-b1f2-e71a87b8f84c"/>
<img src="https://github.com/Headline/discord-compiler-bot/assets/31762830/8a1dec9a-b5db-4ab2-b1a0-26c43216399b"/>
</details>

**Comment by Headline** [comment]
Fixed in [a1ed769](https://github.com/Headline/discord-compiler-bot/commit/a1ed7693b78a318abeb442bf6ee531dca1479608), thanks!
