### ISSUE TITLE
Add support for scala3 (using godbolt)

### ISSUE THREAD

**Issue by LoganTann** [Headline/discord-compiler-bot#223]
Scala3 is now supported by GodBolt

![image](https://github.com/Headline/discord-compiler-bot/assets/28659185/bba09983-0f6b-4fa6-a5f7-cc2ea0886476)

**Comment by ThomasByr** [comment]
as far as i know, as long as new languages are supported by godbolt or wandbox, they will be automatically added when the bot restarts

**Comment by LoganTann** [comment]
Both godbolt and wandbox supports scala, however, wandbox supports only scala 2 and not scala 3

**Comment by Halalaluyafail3** [comment]
This seems to work fine with the compiler name `scalac300`.

**Comment by LoganTann** [comment]
It works! I will close this issue.

(note : there is [a bug](https://github.com/compiler-explorer/compiler-explorer/issues/5520) in godbolt itself that makes the println method unusable in scala 3. I think I will still write my code in scala 2 for now...)
