### ISSUE TITLE
Support for Kotlin lang

### ISSUE THREAD

**Issue by anilmisirlioglu** [Headline/discord-compiler-bot#78]
[Kotlin](https://kotlinlang.org) is used by many developers and continues to grow every year. It may be good to support this language as well.

**Comment by asherkin** [comment]
I believe you'll want to direct this upstream to Wandbox: https://github.com/melpon/wandbox-builder (or PR it yourself!)

**Comment by anilmisirlioglu** [comment]
Thanks, I'll point this to [Wandbox](https://github.com/melpon/wandbox-builder).
