### ISSUE TITLE
The compiler doesn't takes input

### ISSUE THREAD

**Issue by Paradox177** [Headline/discord-compiler-bot#79]
The compiler doesn't takes input in input based programs

**Comment by Headline** [comment]
Hello - can you post an example request that isn’t behaving as expected?

**Comment by Paradox177** [comment]
;compile java
```import java.util.Scanner;
class rs
{
public static void main(String args[])
{
Scanner k=new Scanner(System.in);
System.out.println("Write The no. To be reveresed");
int n=k.nextInt();
int r=0,d;
while(n>0)
{
d=n%10;
r=(r*10)+d;
n=n/10;
}
System.out.println(r);
}
    }```
Ok,this is a sample program for java for discord compiler bot
But, this doesn't works
Cause' input function is disabled
And, can you tell me how to download it's code?

**Comment by Headline** [comment]
Have you read the wiki? It is a detailed tutorial on how to use the bot if you are having trouble.

This explains how standard input is accepted: 

https://github.com/Headline/discord-compiler-bot/wiki/Introduction#using-stdin


There is no way to download the compiled code.

**Comment by Paradox177** [comment]
> Have you read the wiki? It is a detailed tutorial on how to use the bot if you are having trouble.
> 
> This explains how standard input is accepted:
> 
> https://github.com/Headline/discord-compiler-bot/wiki/Introduction#using-stdin
> 
> There is no way to download the compiled code.

**Comment by Paradox177** [comment]
Thank you

**Comment by Headline** [comment]
No worries! If you have any other issues feel free to open another ticket!

**Comment by Paradox177** [comment]
Then,no not the compiled code
But,
The code of this compiler bot
I want to understand it. I'm total new to this

**Comment by Headline** [comment]
Your example will run with the following:
``````
;compile java | 32
```
import java.util.Scanner;
class rs
{
public static void main(String args[])
{
Scanner k=new Scanner(System.in);
System.out.println("Write The no. To be reveresed");
int n=k.nextInt();
int r=0,d;
while(n>0)
{
d=n%10;
r=(r*10)+d;
n=n/10;
}
System.out.println(r);
}
    }
```
``````

**Comment by Headline** [comment]
If you wish to download this projects code - there should be an option to download it as a zip file at the top right of the main page (https://github.com/headline/discord-compiler-bot)

**Comment by Paradox177** [comment]
> Your example will run with the following:
> 
> ```
> ;compile java | 32
> ```
> import java.util.Scanner;
> class rs
> {
> public static void main(String args[])
> {
> Scanner k=new Scanner(System.in);
> System.out.println("Write The no. To be reveresed");
> int n=k.nextInt();
> int r=0,d;
> while(n>0)
> {
> d=n%10;
> r=(r*10)+d;
> n=n/10;
> }
> System.out.println(r);
> }
>     }
> ```
> ```

This one I understood how to take input in a program 
Thanx mery much for your help and time

**Comment by Headline** [comment]
No problem! We also have a support discord server linked below that may be more convenient.

I'm glad to see you are interested in the project and I will be happy to answer any questions you have!

https://discord.com/invite/ExraTaJ
