### ISSUE TITLE
Replace alternate quote chars with compiler-accepted counterparts

### ISSUE THREAD

**Issue by Dhruvin-Purohit** [Headline/discord-compiler-bot#88]
Please consider replacing the following respectively because people on phones cannot use `"` and `'` also iirc those quotes used in phones aren't used in any of the languages for a particular use although you could add an ability that escaped ones aren't replaced

> for example: `“` will be replaced but `\“` won't be.

`“` **->** `"`
`”` **->** `"`
`‘` **->** `'`
`’` **->** `'`

**Comment by Headline** [comment]
Hello! Thanks for opening this issue.

Writing code as a mobile user is difficult, I think doing string replacements here is okay unless anyone passing by has comments regarding it.

**Comment by Dhruvin-Purohit** [comment]
I guess this issue can be closed then? like I don't see anyone using those alternate quote chars instead of compiler accepted counterparts.
